[package]
name = "camel"
version = "0.1.0"
edition = "2024"

[dependencies]
discord-rich-presence = "0.2"
tray-item = "0.10"

[dependencies.windows]
version = "0.52"
features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
]

[build-dependencies]
embed-resource = "2.4"